<?php

namespace CoralScrum\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByTaskId($taskId)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->join('u.userproject', 'us_p')
           ->join('us_p.project', 'p')
           ->join('p.userStory', 'us')
           ->join('us.task', 't')
           ->where('t.id = :taskId')
           ->setParameter('taskId', $taskId)
           ;
        return $qb->getQuery()->getResult();
    }

    public function countUserById($projectId)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('count(u.id)')
           ->leftJoin('u.userproject', 'us_p')
           ->where('us_p.project IS NULL')
           ->orWhere('us_p.project != :projectId')
           ->setParameter('projectId', $projectId)
           ->orderBy('u.username', 'ASC');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
