<?php

namespace CoralScrum\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function getVisibleProject($user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.owner = :user_id')
           ->setParameter('user_id', $user->getId())
           ->orWhere('p.isPublic = 1')
           ;
        return $qb->getQuery()->getResult();
    }
}
