<?php

namespace CoralScrum\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function getVisibleProject($user_id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
           //->join('p.owner', 'u')
           //->addSelect('u')
           ->where('p.owner = 1')
           ->orWhere('p.isPublic = 1')
           //->andWhere('p.owner_id = ?', 1)
            //->setParameter('user_id', $user)
            //->orderBy('p.blocked', 'ASC')
            //->addOrderBy('p.pin', 'DESC')
            //->addOrderBy('u.username', 'ASC')
            ;
        return $qb->getQuery()->getResult();
    }
}
