<?php

namespace CoralScrum\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function getVisibleProject($user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.userproject', 'usp')
           ->where('p.isPublic = 1')
           ->orWhere('usp.user = :user_id')
           ->setParameter('user_id', $user->getId())
           ;
        return $qb->getQuery()->getResult();
    }

    public function findOneByIdJoinedToUser($projectId)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, us_p, u FROM CoralScrumMainBundle:Project p
                LEFT JOIN p.userproject us_p
                LEFT JOIN us_p.user u
                WHERE p.id = :projectId'
            )->setParameter('projectId', $projectId);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function isCreator($projectId, $user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('COUNT(p.id)')
           ->where('p.id = :projectId')
           ->andWhere('p.owner = :user_id')
           ->setParameters(array(
                'projectId' => $projectId,
                'user_id' => $user->getId()
            ));

        return $qb->getQuery()->getSingleScalarResult();
    }
}
