<?php

namespace CoralScrum\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintRepository extends EntityRepository
{
    public function findOneByIdJoined($sprintId)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT sp, us, t, u FROM CoralScrumMainBundle:Sprint sp
                LEFT JOIN sp.userStory us
                LEFT JOIN us.task t
                LEFT JOIN t.user u
                WHERE sp.id = :sprintId'
            )->setParameter('sprintId', $sprintId);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findByIdJoinedToUserStory($projectId)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT sp, us FROM CoralScrumMainBundle:Sprint sp
                JOIN sp.project p
                LEFT JOIN sp.userStory us
                WHERE p.id = :projectId'
            )->setParameter('projectId', $projectId);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
