<?php

namespace CoralScrum\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{
    public function findByProjectIdJoined($projectId)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT t, us, u FROM CoralScrumMainBundle:Test t
                LEFT JOIN t.tester u
                JOIN t.userStory us
                JOIN us.project p
                WHERE p.id = :projectId'
            )->setParameter('projectId', $projectId);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findBySprintId($sprintId)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->join('t.userStory', 'us')
           ->join('us.sprint', 'sp')
           ->where('sp.id = :sprintId')
           ->setParameter('sprintId', $sprintId)
           ;
        return $qb->getQuery()->getResult();
    }

    public function countTestNotPassedByUserStoryId($userStoryId)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('count(t.id)')
           ->join('t.userStory', 'us')
           ->where('us.id = :userStoryId')
           ->andWhere('t.state IN (:state)')
           ->setParameters(array(
               'userStoryId' => $userStoryId,
               'state'  => array(0, 2),
            ))
           ;
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function countByUserStoryId($userStoryId)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('count(t.id)')
           ->join('t.userStory', 'us')
           ->where('us.id = :userStoryId')
           ->setParameter('userStoryId', $userStoryId)
           ;
        return $qb->getQuery()->getSingleScalarResult();
    }
}
