<?php

namespace CoralScrum\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStoryRepository extends EntityRepository
{
    public function countByProjectId($projectId)
    {
        $em = $this->getEntityManager();
        $query = $em
                ->createQuery("
                    SELECT COUNT(us)
                    FROM CoralScrum\MainBundle\Entity\UserStory us
                    WHERE us.project = :projectId
                ")
                ->setParameter('projectId', $projectId);

        return $query->getSingleScalarResult();
    }
}
